---
title: "cma"
author: "PjF"
date: "2023-12-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(cma, data.table)
```

This report is 

```{r}
nosolde_()[abs(value)>49000,.(libelle,value,var,period)]
```


```{r, exception}
nosolde_()[var %like% "exception",.(libelle,value,var,period)][order(-value)] |>
  gt::gt()
```


```{r}
nosolde_()[,.(value=sum(value)),.(group,period)] |>
  dplyr::group_by(group) |>
  dplyr::mutate(value= cumsum(value)) |>
  dplyr::arrange(group,period) |>
  ggplot2::ggplot(mapping= ggplot2::aes(x= period, y=value, color= group)) +
  ggplot2::geom_line()
```

```{r, mseries}


mseries <- nosolde_()[,.(value=sum(value)),.(period,group)]
cseries <- nosolde_()[,.(value=cumsum(value)),.(group,period)]

```

```{r, exception}
mseries[,.(max= max(abs(value))), .(group)]
```


```{r, mseries}
mseries <- nosolde_()[,.(value=sum(value)),.(var,period,group)]
mseries |>
  ggplot2::ggplot(mapping= ggplot2::aes(x= period, y=value, color= group)) +
  ggplot2::geom_point()
```


```{r,  solde_gt}
mini_cube_()[,.(value=sum(value)),.(var,year)][var=="solde"] |> 
  tidyr::pivot_wider(
    names_from = var,
    values_from = c(value)) |>
  gt::gt() |>
  gt::fmt_number(
    columns = solde,
    decimals = 0,
    sep_mark = " ")
```

```{r,  solde_gg}
mini_cube_()[,.(value=sum(value)),.(var,year)][var=="solde"] |>
  ggplot2::ggplot(mapping= ggplot2::aes(x= year, y=value)) +
  ggplot2::geom_point()
```

```{r,  freq}
mini_cube_()[!is.na(code),.(value=sum(value)),.(var,month)] |>
  ggplot2::ggplot(mapping= ggplot2::aes(x= value)) +
  ggplot2::geom_histogram()
```